### ISSUE TITLE
As a video content creator, I would like an easier way to configure youtube channels

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2369]
As a video content creator, I would like an easier way to configure youtube channels

#### Acceptance Criteria:

- [ ] In https://github.com/mitodl/open-video-data, support defining youtube channels in separate files. These should live under a `youtube/` directory like we previously had setup
- [ ] Each file should be a relatively flat data structure
- [ ] Use the github api: https://developer.github.com/v3/repos/contents/#get-contents
- [ ] Support specifying different branches via an environment variable (default to `master`)

These files should follow the format (not the change in structure of the `playlists` items):

```yaml
---
offered_by: OCW
channel_id: $CHANNEL_ID
playlists:
  - id: $PLAYLIST_ID
  - id: $PLAYLIST_ID2
    user_list: no
```
