### ISSUE TITLE
Video Search: Add wildcard id flag

### ISSUE THREAD

**Issue by abeglova** [mitodl/open-discussions#2472]
We will add a `id: wildcard` option to playlists to make it possible to download and make user lists for all playlists in a channel without listing each playlist in the config report individually. We will also add a ignore flag to ignore a playlist

For example:
```
channel_id: some_channel
playlists:
  - id: playlist1
    create_user_list: false
 - id: playlist2
    ignore: true
  -id: wildcard
   create_user_list: true
```

Will add all videos in the playlists in the channel except playlist2 to search and create user lists for every  playlist except playlist1 and playlist2
