### ISSUE TITLE
Add option to specify the user list name in the open-video-data config

### ISSUE THREAD

**Issue by abeglova** [mitodl/open-discussions#2523]
For example
```
---
channel_id: UCPonD0FH2WNnEXyTsYiLWMw
offered_by: Bootcamps
playlists:
  - id: PLQykyC1zr8f_0n3SL9DIhwws8QcJpp7hO
    user_list_title: Custom List Name Bootcamps
```

Would set the title of the user list created for playlist PLQykyC1zr8f_0n3SL9DIhwws8QcJpp7hO to `Custom List Name Bootcamps`
